import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const distDir = path.join(__dirname, 'dist');

// Create CNAME file for custom domain (GitHub Pages)
const cnameFile = path.join(distDir, 'CNAME');
fs.writeFileSync(cnameFile, 'dbtree.app');
console.log('✓ Created CNAME file');

// 404.html is natively generated by Astro from src/pages/404.astro
console.log('✓ Post-build setup complete!');
